### PR TITLE
Remove stray auto-generated config files

### PR DESCRIPTION
**Pull request by lukash**
My apologies, when making #21 I forgot two auto-generated files in git.

That is besides `confparser.h` which I'm still keeping for `balance` and `float`, but I also added a commit to update the `config` example, and there I remove that one as well, as I think it's the correct approach.

(I also didn't touch the new `tnt` package, as @Izzygit isn't using the config auto-generation there)

### CODE REVIEW

**Comment by surfdado** [comment]
What's your handle on discord? how can we talk to you? Plenty of users are struggling to build packages...

**Comment by lukash** [comment]
riddimrider1 on discord. You didn't reply last time I messaged you there :innocent:

**Comment by surfdado** [comment]
Geez, this is what I hate about Discord - people use random-ass names so you have no idea whom you're talking to... Well, I'll try my best to remember now. Also, for people who contribute to github it would be really nice if you could just change your name to match or at least be similar to your github name

**Comment by lukash** [comment]
The discussion on discord died, I've summed up the results so far in #33. This PR is unrelated to the issue, can we proceed with review and merge?

**Pull request closed without merging**
