### PR TITLE
Remove the separate Float package loop frequency setting.

### PR DESCRIPTION
**Pull request by lolwheel**
The frequency is now acquired from IMU app directly. Also implement semaphore-based synchronization between the IMU update thread and Float thread which reduces the jitter and tightens the response time of Float package.

Some housekeeping in this PR as well - sync the vesc_pkg vesc_c_if.h with the BLDC one.

Tested this change, my Floatweel rode fine. Package installation and uninstall also works fine.

This PR goes hand-in-hand with the another one I created against vedderb/bldc that adds
two new functions to `VESC_IF`.

### CODE REVIEW

**Comment by surfdado** [comment]
Why such a change without first talking to any of us on Discord?

Sorry but I have to veto it. There are plenty of users who need to run 832Hz float package frequency and 416Hz IMU frequency. 

Besides, there's a ton of seemingly unrelated changes in this commit - even if I agreed with the proposed new behavior I would ask you to separate this out into multiple commits.

**Comment by Relys** [comment]
> Why such a change without first talking to any of us on Discord?
> 
> Sorry but I have to veto it. There are plenty of users who need to run 832Hz float package frequency and 416Hz IMU frequency.
> 
> Besides, there's a ton of seemingly unrelated changes in this commit - even if I agreed with the proposed new behavior I would ask you to separate this out into multiple commits.

Interesting, what's the use case for running half IMU frequency? I do like the idea of thread frequency synchronization and think this should be explored further. Anyways, good to see you poking around here @lolwheel :)

**Comment by lolwheel** [comment]
> Why such a change without first talking to any of us on Discord?

My bad, I did ask about this in the VESC channel and had Benjamin approve the idea, at least the `bldc` part of it that exposes semaphore APIs, thought you saw it too.

> Sorry but I have to veto it. There are plenty of users who need to run 832Hz float package frequency and 416Hz IMU frequency.

You're the boss. Any reason why you'd want float pkg running faster besides maybe the beeper control? Naively I don't see the point of rerunning the loop with the stale data that's already been processed once.

> Besides, there's a ton of seemingly unrelated changes in this commit - even if I agreed with the proposed new behavior I would ask you to separate this out into multiple commits.

Most of these changes are necessary but you're right, some of it could be left out. Happy to do it if we resolve the other outstanding issues.

Cheers.

**Comment by surfdado** [comment]
Vescify Discord is the best place for OW and Float Package related topics. The 416Hz topic has been discussed more than once there. 

The reason we don't recommend deviating from the ~800 frequency in float/refloat is that Tunes would end up behaving very differently. Several features are dependent on the package frequency. 800 vs 832 is fine to match the different IMUs but going down to 416Hz would cut the I-term intensity in half, and fundamentally change the feel of haptic buzz, as well as impact several other features...

**Comment by lolwheel** [comment]
Okay gotcha, I did see a bunch of divisions by `dT` that I had to rewrite and assumed that all config constants are properly decoupled from the looptime. Sounds like I jumped the gun, I'll look into 

Can you think of other things dependent on the looptime that would require fixing?

**Comment by aeraglyx** [comment]
"Yaw Rate", ERPM acceleration and EMA filters are also affected.

Linking a message on this matter, since people were discussing IMU frequencies at that time:
https://discord.com/channels/846794200308908065/1055198116418166874/1260014565647847495

Yaw Rate can use gyro data (with a multiplier, if we want to keep the Turn Tilt intensity).

I wish my floatwheel wasn't bricked so I could continue testing stuff :(

**Comment by lukash** [comment]
> Interesting, what's the use case for running half IMU frequency? I do like the idea of thread frequency synchronization and think this should be explored further. Anyways, good to see you poking around here @lolwheel :)

FWIW I think the reason people set half IMU frequency is because it somehow alleviates the synchronization issues that this PR is trying to solve properly. If this is submitted against Refloat, I'd make a "feature preview" build for people to try out (I've been meaning to introduce that mechanism so that people can easily download a provide feedback on functional changes to the package) and say if they like the change. I know for example that vescmann has a very particular opinion on running IMU at 416Hz, I think he may have something to say about this.

**Comment by lolwheel** [comment]
I'll close this pull request for now, this feature doesn't bring much to the table in terms of ride feel improvements. I'll be focusing on other stuff.

**Pull request closed without merging**
