### PR TITLE
Trick and Trail v1.0

### PR DESCRIPTION
**Pull request by Izzygit**
A new vesc package for self-balanced boards. Uses a new control scheme, additional IMU filtering, and unique features for trail riding.

### CODE REVIEW

**Comment by surfdado** [comment]
I think this needs some cleanup:
1) the vescpkg binary shouldn't be part of the commits
2) when removing the .vescpkg file it doesn't build, as there's no Makefile
3) within the code the package presents itself identically to the float package - please change the magic number in the FLOAT_COMMAND_GET_INFO command, same for all the other FLOAT_COMMANDS. The magic number should be unique to your package

I'd like to try it out once those issues are resolved

**Comment by Izzygit** [comment]
Thank you for your feedback. I will work on those changes. Some comments
below

1. I was looking in the notes section at the end of the Vesc-pkg readme. It
says to make sure to build a pkg file in the main directory. Maybe I
misunderstood or that is old. Either way, easy fix.
2. I see that I don’t have a make file in the main directory. I assume that
is what you are referring to. I will get on that. Haven’t done that before.
3. Thanks. It was not clear what magic number was for, but my understanding
of the communication is limited so I left it.

Mike

**Comment by surfdado** [comment]
It still doesn't build for me. If you do a make clean and make in vesc_pkg it should build all packages. I shouldn't have to go into the tnt folder and run make.

But even when I do run make in tnt it complains about a missing ui.qml.in

**Comment by surfdado** [comment]
If I copy ui.qml to ui.qml.in then make works in the tnt folder. ui.qml.in is the file that should be in git, not ui.qml - or change the Makefile to just use a static ui.qml

But both make and make clean in the top folder should cover the tnt package.

**Comment by Izzygit** [comment]
Thanks for explaining. I always used Vesc tool to manually make the vscpkg
file. I believe the recent pull request should correct this issue.

I am still not able to make all the pkgs because I am running into a
problem with missing qt plug-ins when the make file calls for Vesc tools. I
can make clean everything though. The fact that you were able to compile it
makes me think it is just my computer. I don’t know much about how qt
creator works so it might take me a bit to get my vm to call Vesc tools
correctly so it auto generates vscpkg files. I think it will work for you.

Thanks
Mike

**Pull request closed without merging**
